In [1]:
import pandas as pd
data=pd.read_excel('JAIS.xlsx')
data.head()

,Title,Year,Issue,ArticleURL,Abstract,Author_Name,Author_University
0,A Knowledge Management Perspective of Generati...,2024,Issue 1,https://aisel.aisnet.org/jais/vol25/iss1/15,No Abstract,Maryam Alavi,Georgia Institute of Technology
1,A Knowledge Management Perspective of Generati...,2024,Issue 1,https://aisel.aisnet.org/jais/vol25/iss1/15,No Abstract,Dorothy E. Leidner,University of Virginia
2,A Knowledge Management Perspective of Generati...,2024,Issue 1,https://aisel.aisnet.org/jais/vol25/iss1/15,No Abstract,Reza Mousavi,University of Virginia
3,The Societal Impacts of Generative Artificial ...,2024,Issue 1,https://aisel.aisnet.org/jais/vol25/iss1/14,No Abstract,Rajiv Sabherwal,University of Arkansas
4,The Societal Impacts of Generative Artificial ...,2024,Issue 1,https://aisel.aisnet.org/jais/vol25/iss1/14,No Abstract,Varun Grover,University of Arkansas

In [18]:
data = data.where(pd.notna(data), None)

In [17]:
data.iloc[[872]]

,Title,Year,Issue,ArticleURL,Abstract,Author_Name,Author_University
872,(Re)considering the Concept of Literature Revi...,2020,Issue 5,https://aisel.aisnet.org/jais/vol21/iss5/10,No Abstract,Guy Pare,HEC Montr√©al

In [3]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2543 entries, 0 to 2542
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Title              2543 non-null   object
 1   Year               2543 non-null   int64
 2   Issue              2543 non-null   object
 3   ArticleURL         2543 non-null   object
 4   Abstract           2543 non-null   object
 5   Author_Name        2542 non-null   object
 6   Author_University  2542 non-null   object
dtypes: int64(1), object(6)
memory usage: 139.2+ KB
None

In [3]:
print(data.isnull().sum())
print(data.describe())
data=data.fillna('Null')

Title                0
Year                 0
Issue                0
ArticleURL           0
Abstract             0
Author_Name          1
Author_University    1
dtype: int64
              Year
count  2543.000000
mean   2015.821471
std       6.300779
min    2000.000000
25%    2011.000000
50%    2017.000000
75%    2021.000000
max    2024.000000

In [4]:
data.duplicated().sum()

0

In [34]:
duplicates = data[data.duplicated(subset=['Author_Name','ArticleURL'], keep='first')]
print(duplicates)

Empty DataFrame
Columns: [Title, Year, Issue, ArticleURL, Abstract, Author_Name, Author_University]
Index: []

In [5]:
data=data.drop_duplicates()

In [2]:
jais_data=pd.read_csv('extract.csv')
jais_data.head()

,URL,Journal_Title,Article_Title,Abstract,Author_name,Standardized_Author,Author_University,Author_State,Author_Country,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,https://aisel.aisnet.org/jais/vol25/iss1/15,Journal of the Association for Information Sys...,A Knowledge Management Perspective of Generati...,No Abstract,Maryam Alavi,Maryam Alavi,Georgia Institute of Technology,Georgia,United States,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://aisel.aisnet.org/jais/vol25/iss1/15,Journal of the Association for Information Sys...,A Knowledge Management Perspective of Generati...,No Abstract,Dorothy E. Leidner,Dorothy E. Leidner,University of Virginia,Virginia,United States,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://aisel.aisnet.org/jais/vol25/iss1/15,Journal of the Association for Information Sys...,A Knowledge Management Perspective of Generati...,No Abstract,Reza Mousavi,Reza Mousavi,University of Virginia,Virginia,United States,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://aisel.aisnet.org/jais/vol25/iss1/14,Journal of the Association for Information Sys...,The Societal Impacts of Generative Artificial ...,No Abstract,Rajiv Sabherwal,Rajiv Sabherwal,University of Arkansas,Arkansas,United States,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://aisel.aisnet.org/jais/vol25/iss1/14,Journal of the Association for Information Sys...,The Societal Impacts of Generative Artificial ...,No Abstract,Varun Grover,Varun Grover,University of Arkansas,Arkansas,United States,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
jais_data = jais_data.where(pd.notna(jais_data), None)
jais_data=jais_data.fillna('Null')

In [4]:
jais_data.duplicated().sum()

0

In [14]:
import pandas as pd
import mysql.connector
import json

# Connect to MySQL
#Used the DSS_new for date matching
db = mysql.connector.connect(
        host=  "127.0.0.1",
        user= "root",
        password="Nanna&143",
        database="journals",
        auth_plugin='mysql_native_password')

cursor = db.cursor()
# Insert data into MySQL
for index, row in jais_data.iterrows():
    articleUrl=row["URL"] if row['URL'] else None
    journal_title=row["Journal_Title"] if row['Journal_Title'] else None
    article_title=row["Article_Title"] if row['Article_Title'] else None
    # abstract=row["Abstract"] if row['Abstract'] else None
    # Year=row["Year"] if row['Year'] else None
    Author_University=row["Author_University"] if row['Author_University'] else None
    Author_Name=row["Author_name"] if row['Author_name'] else None
    standardized_author=row["Standardized_Author"] if row['Standardized_Author'] else None
    # author_email=row["Author_email"] if row['Author_email'] else None
    # author_address=row["Author_Address"] if row['Author_Address'] else None
    author_university=row["Author_University"] if row['Author_University'] else None
    # author_department=row["Author_department"] if row['Author_department'] else None
    author_state=row["Author_State"] if row['Author_State'] else None  #   
    author_country=row["Author_Country"] if row['Author_Country'] else None
        
    try:
        sql = """
        INSERT INTO JAIS_DATA(URL,Journal_Title,Article_Title,Author_Name,Standardized_Author,Author_University,Author_State,Author_Country) values(%s, %s, %s, %s, %s, %s, %s, %s)
        """
        values = (
            articleUrl,
            journal_title,
            article_title,
            Author_Name,
            standardized_author,
            author_university,
            author_state,
            author_country

        )
        
        cursor.execute(sql, values)
    except Exception as e:
        print(f"Error inserting data: {e}{row["URL"]}")
        break
# Commit & close connection
db.commit()
cursor.close()
db.close()

print("Data inserted successfully!")

Data inserted successfully!

In [9]:
#For the decision support systems titles
import pandas as pd
import mysql.connector
import json

#connect to mysql
db=mysql.connector.connect(
    host="127.0.0.1",
    user='root',
    password='Nanna&143',
    database='journals',
    auth_plugin='mysql_native_password'
)
cursor=db.cursor()
for index, row in df.iterrows():
    title = row["Title"] if row["Title"] else None
    url = row["URL"] if row["URL"] else None
    vol_year=row["Year"] if row["Year"] else None

    try:
        sql = """
        INSERT INTO JSIS_Articles
        (Article_Title, URL, Month_Year)
        VALUES (%s, %s, %s)
        """
        values = (title, url, vol_year)
        cursor.execute(sql, values)
    except Exception as e:
        print(f"Error inserting data: {e} {row['Title']}")
        break

db.commit()
cursor.close()
db.close()

In [15]:
import mysql.connector
import pandas as pd

db = mysql.connector.connect(
        host=  "127.0.0.1",
        user= "root",
        password="Nanna&143",
        database="journals",
        auth_plugin='mysql_native_password')

# Define the SQL query
query = "SELECT * FROM JAIS_DATA"

# Read data into a Pandas DataFrame
df = pd.read_sql(query, db)

# Export DataFrame to Excel
df.to_excel("JAIS_final.xlsx", index=False, engine="openpyxl")

# Close the database connection
db.close()

print("Data exported successfully to Journal_Articles.xlsx")

Data exported successfully to Journal_Articles.xlsx

/var/folders/pk/rsrc4d3x4vdgqzfqp8r7lw080000gn/T/ipykernel_1968/4183485856.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, db)