In [1]:
import pandas as pd
data=pd.read_excel('JAIS.xlsx')
data.head()

,Title,Year,Issue,ArticleURL,Abstract,Author_Name,Author_University
0,A Knowledge Management Perspective of Generati...,2024,Issue 1,https://aisel.aisnet.org/jais/vol25/iss1/15,No Abstract,Maryam Alavi,Georgia Institute of Technology
1,A Knowledge Management Perspective of Generati...,2024,Issue 1,https://aisel.aisnet.org/jais/vol25/iss1/15,No Abstract,Dorothy E. Leidner,University of Virginia
2,A Knowledge Management Perspective of Generati...,2024,Issue 1,https://aisel.aisnet.org/jais/vol25/iss1/15,No Abstract,Reza Mousavi,University of Virginia
3,The Societal Impacts of Generative Artificial ...,2024,Issue 1,https://aisel.aisnet.org/jais/vol25/iss1/14,No Abstract,Rajiv Sabherwal,University of Arkansas
4,The Societal Impacts of Generative Artificial ...,2024,Issue 1,https://aisel.aisnet.org/jais/vol25/iss1/14,No Abstract,Varun Grover,University of Arkansas

In [2]:
data = data.where(pd.notna(data), None)

In [3]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2551 entries, 0 to 2550
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Title              2551 non-null   object
 1   Year               2551 non-null   int64
 2   Issue              2551 non-null   object
 3   ArticleURL         2551 non-null   object
 4   Abstract           2551 non-null   object
 5   Author_Name        2550 non-null   object
 6   Author_University  2550 non-null   object
dtypes: int64(1), object(6)
memory usage: 139.6+ KB
None

In [4]:
print(data.isnull().sum())
print(data.describe())
data=data.fillna('Null')

Title                0
Year                 0
Issue                0
ArticleURL           0
Abstract             0
Author_Name          1
Author_University    1
dtype: int64
              Year
count  2551.000000
mean   2015.831439
std       6.293399
min    2000.000000
25%    2011.000000
50%    2018.000000
75%    2021.000000
max    2024.000000

In [2]:
#The first version to get the years of articles
import pandas as pd
df=pd.read_csv('Journal_of_SIS.csv')
df['Year'] = df['Month_Year'].apply(lambda x: x.split(" ")[-1])
df.head()
# Convert manually after reading

,Title,URL,Volume Issue,Month_Year,Year
0,Responsible artificial intelligence governance...,https://www.sciencedirect.com/science/article/...,"Volume 34, Issue 2",01 June 2025,2025
1,The complementary and substitutional effects o...,https://www.sciencedirect.com/science/article/...,"Volume 34, Issue 1",01 March 2025,2025
2,A socio-cognitive perspective of knowledge int...,https://www.sciencedirect.com/science/article/...,"Volume 34, Issue 1",01 March 2025,2025
3,A process model for design-oriented machine le...,https://www.sciencedirect.com/science/article/...,"Volume 34, Issue 1",01 March 2025,2025
4,A knowledge-centric model for government-orche...,https://www.sciencedirect.com/science/article/...,"Volume 34, Issue 1",01 March 2025,2025

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048 entries, 0 to 1047
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Title         1048 non-null   object
 1   URL           1048 non-null   object
 2   Volume Issue  1048 non-null   object
 3   Month_Year    1048 non-null   object
 4   Year          1048 non-null   object
dtypes: object(5)
memory usage: 41.1+ KB

In [4]:

df = df.fillna('NULL')

In [8]:
# print(data['Author_Country'].value_counts())

In [5]:
df.duplicated().sum()

0

In [6]:
df.head()

,Title,URL,Volume Issue,Month_Year,Year
0,Responsible artificial intelligence governance...,https://www.sciencedirect.com/science/article/...,"Volume 34, Issue 2",01 June 2025,2025
1,The complementary and substitutional effects o...,https://www.sciencedirect.com/science/article/...,"Volume 34, Issue 1",01 March 2025,2025
2,A socio-cognitive perspective of knowledge int...,https://www.sciencedirect.com/science/article/...,"Volume 34, Issue 1",01 March 2025,2025
3,A process model for design-oriented machine le...,https://www.sciencedirect.com/science/article/...,"Volume 34, Issue 1",01 March 2025,2025
4,A knowledge-centric model for government-orche...,https://www.sciencedirect.com/science/article/...,"Volume 34, Issue 1",01 March 2025,2025

In [24]:
import pandas as pd
import mysql.connector
import json

# Connect to MySQL
#Used the DSS_new for date matching
db = mysql.connector.connect(
        host=  "127.0.0.1",
        user= "root",
        password="Nanna&143",
        database="journals",
        auth_plugin='mysql_native_password')

cursor = db.cursor()
# Insert data into MySQL
for index, row in data.iterrows():
    url=row["URL"] if row['URL'] else None
    article_title=row["Article_Title"] if row['Article_Title'] else None
    journal_title=row["Journal_Title"] if row['Journal_Title'] else None
    abstract=row["Abstract"] if row['Abstract'] else None
    keywords = json.dumps(row['Keywords']) if row['Keywords'] else None  # Handle JSON
    # month_year=row["Month_Year"] if row['Month_Year'] else None
    author_name=row["Author_name"] if row['Author_name'] else None
    standard_name=row["Standardized_Author"] if row['Standardized_Author'] else None
    author_email=row["Author_email"] if row['Author_email'] else None
    author_address=row["Author_Address"] if row['Author_Address'] else None
    author_university=row["Author_University"] if row['Author_University'] else None
    author_department=row["Author_department"] if row['Author_department'] else None
    author_state=row["Author_State"] if row['Author_State'] else None  #   
    author_country=row["Author_Country"] if row['Author_Country'] else None
        
    try:
        sql = """
        INSERT INTO JSIS(URL,Journal_Title,Article_Title,Abstract,Keywords,Author_Name,Standardized_Author,Author_Email,Author_Address,Author_University,Author_Department,Author_State,Author_Country) values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
        """
        values = (
            url,journal_title,article_title,abstract,keywords,author_name,standard_name,author_email,author_address,author_university,author_department,author_state,author_country
        )
        
        cursor.execute(sql, values)
    except Exception as e:
        print(f"Error inserting data: {e}{row["URL"]}")
        break
# Commit & close connection
db.commit()
cursor.close()
db.close()

print("Data inserted successfully!")

Data inserted successfully!

In [9]:
#For the decision support systems titles
import pandas as pd
import mysql.connector
import json

#connect to mysql
db=mysql.connector.connect(
    host="127.0.0.1",
    user='root',
    password='Nanna&143',
    database='journals',
    auth_plugin='mysql_native_password'
)
cursor=db.cursor()
for index, row in df.iterrows():
    title = row["Title"] if row["Title"] else None
    url = row["URL"] if row["URL"] else None
    vol_year=row["Year"] if row["Year"] else None

    try:
        sql = """
        INSERT INTO JSIS_Articles
        (Article_Title, URL, Month_Year)
        VALUES (%s, %s, %s)
        """
        values = (title, url, vol_year)
        cursor.execute(sql, values)
    except Exception as e:
        print(f"Error inserting data: {e} {row['Title']}")
        break

db.commit()
cursor.close()
db.close()

In [25]:
import mysql.connector
import pandas as pd

db = mysql.connector.connect(
        host=  "127.0.0.1",
        user= "root",
        password="Nanna&143",
        database="journals",
        auth_plugin='mysql_native_password')

# Define the SQL query
query = "SELECT * FROM JSIS"

# Read data into a Pandas DataFrame
df = pd.read_sql(query, db)

# Export DataFrame to Excel
df.to_excel("JSIS_final.xlsx", index=False, engine="openpyxl")

# Close the database connection
db.close()

print("Data exported successfully to Journal_Articles.xlsx")

/var/folders/pk/rsrc4d3x4vdgqzfqp8r7lw080000gn/T/ipykernel_31214/922654084.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, db)

Data exported successfully to Journal_Articles.xlsx